### ISSUE TITLE
4.1.0 produces html-formatted "...@glimmer/resolver was not found..."-error on `npm install` on jenkins

### ISSUE THREAD

**Issue by arnebit** [ember-cli/ember-resolver#187]
Our jenkins-jobs fail consistently after updating ember-resolver to the latest version. Running `ember build` on a local machine works without problem with ember-resolver 4.1.0, but on our build server I get the error message below. Downgrading to 4.0.0 makes it go away.

```
+ npm install
npm ERR! registry error parsing json
[...2 fsevents-related warnings removed]
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /repository/npm-group/@glimmer/resolver was not found on this server.</p>
npm ERR! </body></html>
[...]
```

**Comment by baron1405** [comment]
I am also experiencing the same problem. Upgraded from ember-cli 2.12.2 to 2.13.1 and had this happen when performing `ember build`:
```Command failed: npm install --no-optional --loglevel error
    npm ERR! registry error parsing json
    npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
    npm ERR! argv "/home/baron/projects/gradle-webapp-plugins/build/testProjects/cthing2771934566394851697/.gradle/nodejs/node-v6.10.3-linux-x64/bin/node" "/home/baron/projects/gradle-webapp-plugins/build/testProjects/cthing2771934566394851697/.gradle/nodejs/node-v6.10.3-linux-x64/bin/npm" "install" "--no-optional" "--loglevel error"
    npm ERR! node v6.10.3
    npm ERR! npm  v3.10.10

    npm ERR! Unexpected token < in JSON at position 0
    npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    npm ERR! <html><head>
    npm ERR! <title>404 Not Found</title>
    npm ERR! </head><body>
    npm ERR! <h1>Not Found</h1>
    npm ERR! <p>The requested URL /nexus/content/groups/npm-all/@glimmer/resolver was not found on this server.</p>
    npm ERR! </body></html>
    npm ERR! 
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/baron/projects/gradle-webapp-plugins/build/testProjects/cthing2771934566394851697/npm-debug.log

    Error: Command failed: npm install --no-optional --loglevel error
    npm ERR! registry error parsing json
    npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
    npm ERR! argv "/home/baron/projects/gradle-webapp-plugins/build/testProjects/cthing2771934566394851697/.gradle/nodejs/node-v6.10.3-linux-x64/bin/node" "/home/baron/projects/gradle-webapp-plugins/build/testProjects/cthing2771934566394851697/.gradle/nodejs/node-v6.10.3-linux-x64/bin/npm" "install" "--no-optional" "--loglevel error"
    npm ERR! node v6.10.3
    npm ERR! npm  v3.10.10

    npm ERR! Unexpected token < in JSON at position 0
    npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    npm ERR! <html><head>
    npm ERR! <title>404 Not Found</title>
    npm ERR! </head><body>
    npm ERR! <h1>Not Found</h1>
    npm ERR! <p>The requested URL /nexus/content/groups/npm-all/@glimmer/resolver was not found on this server.</p>
    npm ERR! </body></html>
    npm ERR! 
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/baron/projects/gradle-webapp-plugins/build/testProjects/cthing2771934566394851697/npm-debug.log

        at Promise.all.then.arr (/home/baron/projects/gradle-webapp-plugins/build/testProjects/cthing2771934566394851697/node_modules/execa/index.js:210:11)
        at process._tickCallback (internal/process/next_tick.js:109:7)
```
I am using Sonatype Nexus as a proxy for the npm repo at https://registry.npmjs.org.

**Comment by stefanpenner** [comment]
`@glimmer/resolver` isn't related to this project.

**Comment by rwjblue** [comment]
@stefanpenner @glimmer/resolver is a dep of this project, and is enabled via a feature flag

**Comment by rwjblue** [comment]
However, these errors do seem to be the result of an issue with npm or npm proxies and there's really not much we can do here.

**Comment by baron1405** [comment]
For anyone else who finds this issues, here is how I resolved it. My artifacts are hosted on a Nexus OSS 2 server which is fronted by Apache. The first step is to upgrade Nexus to version 2.14.4 or higher or use Nexus OSS 3. This equips Nexus to handle scoped npm packages. The second step is to add "AllowEncodedSlashes NoDecode" to the Apache conf. This equips Apache to handle the encoded slashes passed by npm.
