### ISSUE TITLE
An error occurred in the constructor for ember-resolver

### ISSUE THREAD

**Issue by faisalforcode** [ember-cli/ember-resolver#234]
ember install ember-ajax
Unexpected identifier

Stack Trace and Error Report: C:\Users\Arif\AppData\Local\Temp/error.dump.bb02d549acb6a432727edeca95447db5.log
An error occurred in the constructor for ember-resolver at C:\Users\Arif\Desktop\pickYourCar\node_modules\ember-resolver
=================================================================================

ENV Summary:

  TIME: Mon May 07 2018 01:57:58 GMT-0700 (Pacific Summer Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\Arif\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - install
  - ember-ajax
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\Arif\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Users\Arif\bin;C
  - \Program Files\Git\mingw64\bin;C
  - \Program Files\Git\usr\local\bin;C
  - \Program Files\Git\usr\bin;C
  - \Program Files\Git\usr\bin;C
  - \Program Files\Git\mingw64\bin;C
  - \Program Files\Git\usr\bin;C
  - \Users\Arif\bin;C
  - \ProgramData\Oracle\Java\javapath;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0;C
  - \Program Files\Intel\WiFi\bin;C
  - \Program Files\Common Files\Intel\WirelessCommon;C
  - \Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C
  - \Program Files\Git\cmd;C
  - \Program Files\nodejs;C
  - \Users\Arif\AppData\Local\Microsoft\WindowsApps;C
  - \Program Files\Intel\WiFi\bin;C
  - \Program Files\Common Files\Intel\WirelessCommon;C
  - \Users\Arif\AppData\Roaming\npm;C
  - \Program Files\MongoDB\Server\3.6\bin;C
  - \Program Files\MongoDB\Server\3.6\bin;C
  - \Program Files\Git\usr\bin\vendor_perl;C
  - \Program Files\Git\usr\bin\core_perl
  PLATFORM: win32 x64
  FREEMEM: 816848896
  TOTALMEM: 4170145792
  UPTIME: 369544.2824034
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz - 2394
  - Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz - 2394
  - Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz - 2394
  - Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz - 2394
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.7.0
  - icu: 60.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.10.0
  - openssl: 1.0.2n
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.50
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Unexpected identifier
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Unexpected identifier
  - name: SyntaxError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: C:\Users\Arif\Desktop\pickYourCar\config\environment.js:10
    EmberENV: {
    ^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Project.require (C:\Users\Arif\Desktop\pickYourCar\node_modules\ember-cli\lib\models\project.js:330:12)

=================================================================================

**Comment by faisalforcode** [comment]
Fixed there was an extra environment Vsriable at wrong place
